FROM node:16

RUN mkdir -p /usr/src/app/backend

WORKDIR /usr/src/app/backend

# Install deps first so docker can cache them
COPY package*.json ./
RUN npm install

COPY . .

# Expose port to access server
EXPOSE 5000
CMD [ "npm", "start"]
